# Generated by Django 6.1.1 on 2026-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModelOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('planner', 'Framey (planning)'), ('production', 'Reel (production)')], max_length=20, unique=True)),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], max_length=20)),
                ('model', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(blank=True, choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], max_length=20)),
                ('default_model', models.CharField(blank=True, max_length=200)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('system', 'System'), ('dark', 'Dark'), ('light', 'Light')], default='system', max_length=10)),
                ('elevenlabs_voice_id', models.CharField(blank=True, max_length=64)),
                ('elevenlabs_voice_name', models.CharField(blank=True, max_length=120)),
                ('elevenlabs_model_id', models.CharField(default='eleven_multilingual_v2', max_length=64)),
                ('elevenlabs_stability', models.FloatField(blank=True, null=True)),
                ('elevenlabs_similarity_boost', models.FloatField(blank=True, null=True)),
                ('elevenlabs_style', models.FloatField(blank=True, null=True)),
                ('elevenlabs_speed', models.FloatField(blank=True, null=True)),
                ('elevenlabs_speaker_boost', models.BooleanField(blank=True, null=True)),
                ('elevenlabs_music_model', models.CharField(default='music_v2', max_length=32)),
                ('pexels_media_type', models.CharField(default='video', max_length=10)),
                ('pexels_orientation', models.CharField(blank=True, default='portrait', max_length=10)),
                ('pexels_size', models.CharField(blank=True, max_length=10)),
                ('onboarding_step', models.CharField(default='welcome', max_length=20)),
                ('onboarding_skipped', models.JSONField(blank=True, default=list)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app settings',
                'verbose_name_plural': 'app settings',
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('elevenlabs', 'ElevenLabs'), ('pexels', 'Pexels')], max_length=20, unique=True)),
                ('encrypted_key', models.TextField()),
                ('key_hint', models.CharField(blank=True, max_length=8)),
                ('last_test_status', models.CharField(choices=[('untested', 'Not tested'), ('valid', 'Valid'), ('failed', 'Failed')], default='untested', max_length=10)),
                ('last_test_message', models.CharField(blank=True, max_length=500)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedSettingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('candidates', models.JSONField(default=list)),
                ('current_summary', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group',), name='unique_pending_import_choice')],
            },
        ),
    ]
