# Generated by Django 6.1.1 on 2026-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='edge_pitch',
            field=models.SmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='edge_rate',
            field=models.SmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='edge_voice',
            field=models.CharField(db_default='en-US-EmmaMultilingualNeural', default='en-US-EmmaMultilingualNeural', max_length=80),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='edge_voice_label',
            field=models.CharField(blank=True, db_default='', max_length=160),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='edge_volume',
            field=models.SmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='narration_provider',
            field=models.CharField(choices=[('edge', 'Free — Edge TTS'), ('elevenlabs', 'ElevenLabs')], db_default='edge', default='edge', max_length=12),
        ),
    ]
