# Generated by Django 6.1.1 on 2026-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='orchestrator_personality',
            field=models.CharField(choices=[('director', 'Director'), ('creative_partner', 'Creative Partner')], db_default='director', default='director', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentmodeloverride',
            name='persona',
            field=models.CharField(choices=[('planner', 'Orchestrator and writing'), ('production', 'Visual specialist')], max_length=20, unique=True),
        ),
    ]
