# Generated by Django 6.1.1 on 2026-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_orchestrator_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredential',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('elevenlabs', 'ElevenLabs'), ('pexels', 'Pexels'), ('pixabay', 'Pixabay'), ('brave', 'Brave Search')], max_length=20, unique=True),
        ),
    ]
