# Generated by Django 6.1.1 on 2026-10-03 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Conversation reply'), ('production', 'Production pipeline'), ('agent', 'Single agent'), ('render', 'Render')], max_length=20)),
                ('agent', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('input', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('usage', models.JSONField(default=list)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('boot_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='studio.generationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled project', max_length=120)),
                ('title_locked', models.BooleanField(default=False)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='studio_proj_updated_4864c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('legacy_id',), name='unique_legacy_project')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('persona', models.CharField(blank=True, max_length=20)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='studio.generationjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='studio.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='studio.project'),
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=30)),
                ('agent', models.CharField(blank=True, max_length=40)),
                ('persona', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.generationjob')),
            ],
            options={
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('job', 'seq'), name='unique_job_event_seq')],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='studio.generationjob')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='studio.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='studio_medi_created_54f50d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['-created_at'], name='studio_gene_created_841c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status'], name='studio_gene_status_fcecbf_idx'),
        ),
    ]
