# Generated by Django 6.1.1 on 2026-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='narration_provider',
            field=models.CharField(blank=True, db_default='', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='narration_voice',
            field=models.CharField(blank=True, db_default='', max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='narration_voice_label',
            field=models.CharField(blank=True, db_default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('chat', 'Conversation reply'), ('production', 'Production pipeline'), ('agent', 'Single agent'), ('render', 'Render'), ('narration', 'Narration')], max_length=20),
        ),
    ]
