# Generated by Django 6.1.1 on 2026-10-03 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_narration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('specialist', models.CharField(max_length=20)),
                ('objective', models.CharField(blank=True, max_length=600)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('expected_output', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('completed', 'Completed'), ('verified', 'Verified'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('invalidated', 'Invalidated')], default='proposed', max_length=12)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('output', models.JSONField(blank=True, null=True)),
                ('artifact_ids', models.JSONField(blank=True, default=list)),
                ('error', models.JSONField(blank=True, null=True)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='attribution',
            field=models.CharField(blank=True, db_default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='candidate_id',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='checksum',
            field=models.CharField(blank=True, db_default='', db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='creator',
            field=models.CharField(blank=True, db_default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='creator_url',
            field=models.URLField(blank=True, db_default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='license',
            field=models.CharField(blank=True, db_default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='license_url',
            field=models.URLField(blank=True, db_default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='metadata',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='mime',
            field=models.CharField(blank=True, db_default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='provider',
            field=models.CharField(blank=True, db_default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='rights_status',
            field=models.CharField(blank=True, db_default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='role',
            field=models.CharField(blank=True, db_default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_page_url',
            field=models.URLField(blank=True, db_default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_url',
            field=models.URLField(blank=True, db_default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(blank=True, db_default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='user_supplied',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='personality',
            field=models.CharField(blank=True, db_default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum', ''), _negated=True), fields=('project', 'checksum'), name='unique_project_checksum'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='studio.generationjob'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studio.project'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['project', 'stage', '-created_at'], name='studio_prod_project_61d22a_idx'),
        ),
        migrations.AddConstraint(
            model_name='productiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project', 'stage'), name='one_active_task_per_stage'),
        ),
    ]
