# Generated by Django 6.1.1 on 2026-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_persona_to_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('chat', 'Conversation reply'), ('production', 'Production pipeline'), ('agent', 'Single agent'), ('render', 'Render'), ('narration', 'Narration'), ('image_check', 'Image check')], max_length=20),
        ),
    ]
